positivepets/urls.py
"""
    URL categories are referenced here roughly in the order they appear in the Nav Bar
"""

from . import views

from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

# for icon redirect
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

app_name = 'positivepets'

urlpatterns = [

    # USER #
    url(r'^$', views.profile_views.redirect),
    url(r'^profile/(?P<friend_id>[0-9]+)/(?P<action>edit_bio|show|edit_picture)/$', views.profile_views.ProfileView.as_view(), name='profile'),
    url(r'^profile/user_picture_save/$', views.profile_views.user_picture_save, name='user_picture_save'),
    url(r'^profile/user_picture_edit/$', views.profile_views.user_picture_edit, name='user_picture_edit'),
    url(r'^profile/bio_save/$', views.profile_views.bio_save, name='bio_save'),
    url(r'^profile/bio_edit/$', views.profile_views.bio_edit, name='bio_edit'),
    url(r'^profile/color_change/$', views.profile_views.color_change_view, name='color_change_view'),
    url(r'^profile/color_save/$', views.profile_views.color_save_view, name='color_save_view'),
    url(r'^profile/change_active_group/(?P<redirect>(chat|email|profile|pet_detail))/(?P<pet_id>[0-9]+)/$', views.misc_views.change_active_group, name='change_active_group'),

    # USER PETS #
    url(r'^user_pet/(?P<friend_id>[0-9]+)/$', views.pet_views.user_pets_show, name='user_pets_show'),
    url(r'^user_pet/add/$', views.pet_views.PetCreate.as_view(), name='pet_add'),
    url(r'^user_pet/update/(?P<pk>[0-9]+)/$', views.pet_views.PetUpdate.as_view(), name='pet_update'),
    url(r'^user_pet/delete/(?P<pk>[0-9]+)/delete/$', views.pet_views.PetDelete.as_view(), name='pet_delete'),

    # PET DETAIL #
    url(r'^pet_detail/(?P<pk>[0-9]+)/(?P<action>(edit|show))/$', views.pet_views.PetDetailView.as_view(), name='pet_detail'),
    url(r'^pet_detail/pet_description_save/(?P<pet_id>[0-9]+)/$', views.pet_views.pet_description_save, name='pet_description_save'),
    url(r'^pet_detail/pet_description_edit/(?P<pet_id>[0-9]+)/$', views.pet_views.pet_description_edit, name='pet_description_edit'),
    url(r'^pet_detail/pet_comment_message_create/(?P<action>(submit|refresh))/(?P<pet_id>[0-9]+)/$',
        views.pet_views.pet_comment_message_create, name='pet_comment_message_create'),

    # CHAT #
    # /positivepets/chatroom/new/
    url(r'chatroom/(?P<action>(submit|refresh))/$', views.chat_views.chat_message_create, name='chatmessage_create'),

    # EMAIL #
    # /positivepets/email/
    url(r'email/folder/(?P<folder>(inbox|sent_mail|))$', views.email_views.email_folder_show, name='email_folder_show'),
    url(r'email/read/(?P<email_id>[0-9]+)/$', views.email_views.email_read_show, name='email_read_show'),
    url(r'email/compose/(?P<reply_type>(none|reply|reply-all))/(?P<email_id>[0-9]+)/$', views.email_views.email_compose_show, name='email_compose_show'),
    url(r'email/send/$', views.email_views.email_send, name='email_send'),

    # ANIMAL SHELTER#
    url(r'^animal_shelter/$', views.animal_shelter_views.animal_shelter_show, name='animal_shelter_show'),
    url(r'^animal_shelter/google_search/$', views.animal_shelter_views.animal_shelter_google_search, name='animal_shelter_google_search'),
    url(r'^animal_shelter/adopt/$', views.animal_shelter_views.animal_shelter_adopt, name='animal_shelter_adopt'),

    # ABOUT #
    # /positivepets/about/
    url(r'^about/$', views.misc_views.about_view, name='about'),

    # ADMIN #
    url(r'^register/$', views.misc_views.UserFormView.as_view(), name='register'),
    url(r'^group/$', views.misc_views.group_admin_show, name='group_admin_show'),
    url(r'^group/add/$', views.misc_views.group_add_view, name='group_add_view'),

    #ICON
    url(r'^pawprint.ico$', RedirectView.as_view(url=staticfiles_storage.url('images/pawprint.ico')), name="pawprint"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.contrib import admin
#from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from positivepets.views.profile_views import redirect

urlpatterns = [
    url(r'^$', redirect),
    url(r'^admin/', admin.site.urls),
    url(r'^positivepets/', include('positivepets.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

positivepets/views/animal_shelter_views.py
import csv, json, io, os, uuid, requests, urllib.request
from collections import defaultdict
from PIL import Image
from bs4 import BeautifulSoup
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from positivepets.models import Pet
from positivepets.utils.colors import color_map

def animal_shelter_google_search(request):
    if request.POST:
        animal_type = request.POST['animal_type']
        breed = request.POST['breed']
        baby_or_fullgrown = request.POST['baby_or_fullgrown']
        key_word_string = animal_type + '+' + breed + "+" + baby_or_fullgrown

        user_search_words = request.POST['search_words']
        if user_search_words:
            user_search_words = ('+'.join(user_search_words.split()) if user_search_words else "")
            key_word_string = key_word_string + "+" + user_search_words

        search_url = "https://www.google.com/search?tbm=isch&q=" + key_word_string + "&safe=active"
        source = requests.get(search_url).text
        soup = BeautifulSoup(source, 'lxml')
        img_list = []
        for img in soup.find_all('img'):
            img_list.append(img['src'])

    json_breeds, json_animals = get_json_info()

    context = {'json_animals': json_animals, 'json_breeds': json_breeds, "image_list":img_list, 'color':request.user.color}
    context['button_text_color'] = color_map[request.user.color.lower()]['button_text_color']
    return render(request, 'positivepets/animal_shelter.html', context)

def get_json_info():
    static_root = getattr(settings, "STATIC_ROOT", "")
    path = os.path.join(static_root, 'breeds.csv')
    csv_file = open(path, encoding='ISO-8859-1')
    reader = csv.DictReader(csv_file)
    animal_names = reader.fieldnames
    breed_dict = defaultdict(list)

    for row in reader:
        for j in range(0,len(row)):
            if row[animal_names[j]] != "":
                breed_dict[animal_names[j]].append(row[animal_names[j]])

    json_breeds = json.dumps(breed_dict)
    json_animals = json.dumps(animal_names)
    return json_breeds, json_animals

def animal_shelter_show(request):
    json_breeds, json_animals = get_json_info()
    context = {'json_animals': json_animals, 'json_breeds':json_breeds, 'color':request.user.color}
    context['button_text_color'] = color_map[request.user.color.lower()]['button_text_color']
    print(json_animals)
    return render(request, 'positivepets/animal_shelter.html',context)

def animal_shelter_adopt(request):

    if request.method == 'POST':
        pet = Pet()
        pet.name = request.POST['adopted_pet_name']
        pet.type = request.POST['selected_animal']
        pet.breed = request.POST['selected_breed']
        pet.user = request.user
        url = request.POST['url']

        if url != "":
            path = io.BytesIO(urllib.request.urlopen(url).read())
            img = Image.open(path)
            pet.picture.name = pet.name + str(uuid.uuid4()) + '.jpg'
            img.save(os.path.join(settings.MEDIA_ROOT, pet.picture.name))
            pet.save()
            return HttpResponseRedirect(reverse('positivepets:user_pets_show', kwargs={'friend_id': request.user.id}))

    return HttpResponseRedirect(reverse('positivepets:user_pets_show', kwargs={'friend_id': request.user.id}))

positivepets/views/chat_views.py
from positivepets.models import Chat, FriendGroup, UserState
from datetime import datetime
from django.shortcuts import render
from positivepets.utils.utils import get_active_friendgroup
from positivepets.utils.colors import color_map
from dateutil import tz

def chat_message_create(request, action):

    context = {}

    # ActiveGroup DropDown List:  1.  get all groups 2. get active group
    user_friend_groups = FriendGroup.objects.filter(friendgroupuser__user__id = request.user.id)
    selected_friend_group = FriendGroup.objects.get(id=UserState.objects.get(user = request.user).ref_id)
    context['user_friend_groups'] = user_friend_groups
    context['selected_friend_group'] = selected_friend_group

    if action == 'submit':
        if request.method == 'POST':
            msg = Chat()
            msg.timestamp = datetime.now()
            msg.user = request.user
            msg.comment = request.POST['textbox']
            msg.group = selected_friend_group
            msg.pet_id = 1
            msg.save()

    now = datetime.now()    #to_zone = tz.tzlocal()
    to_zone = tz.gettz("America/New_York")

    user_list = get_active_friendgroup(request.user.id)
    comment_list = Chat.objects.filter(user_id__in=user_list).filter(group=selected_friend_group.id).filter(pet_id=1).order_by('-timestamp')[:30]  # no neg indexing
    context['comment_list'] = comment_list
    context['button_text_color'] = color_map[request.user.color.lower()]['button_text_color']

    for comment in comment_list:
        comment.timestamp = comment.timestamp.astimezone(to_zone)

    context['user'] = request.user
    context['now'] = now
    context['color'] = request.user.color

    return render(request, 'positivepets/chat_form.html', context)

positivepets/views/detail_views.py
from django.views import generic
from positivepets.models import Pet, CustomUser
from positivepets.forms import PetDescriptionForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from .colors import color_map

class DetailView(generic.DetailView):
    model = Pet
    template_name = 'positivepets/detail.html'
    fields = ['description']

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        pet_id = self.kwargs['pk']
        edit = self.kwargs['edit']
        pet = Pet.objects.get(id=pet_id)
        owner = CustomUser.objects.get(id=pet.user.id)
        description = pet.description
        context['owner'] = owner
        context['description'] = description
        context['edit'] = edit
        try:
            context['color'] = self.request.user.color
            context['button_text_color'] = color_map[self.request.user.color.lower()]['button_text_color']
        except:
            context['color'] = 'lightgray'
            context['button_text_color'] = 'rgb(40,40,40)'

        return context

def description_edit(request, pk):
    if request.method == 'POST':
        url = reverse('positivepets:detail', kwargs={'pk': pk, 'edit': 1})
        return HttpResponseRedirect(url)


def description_save(request, pk):
    if request.method == 'POST':
        form = PetDescriptionForm(request.POST)
        if form.is_valid():
            a = Pet.objects.get(id=pk)
            a.description = form.data['bigtext']
            a.save()
            url = reverse('positivepets:detail', kwargs={'pk': pk, 'edit': 0})
            return HttpResponseRedirect(url)
    else:
        form = PetDescriptionForm()

    return HttpResponseRedirect(reverse('positivepets:detail', kwargs={'pk': pk, 'edit': 0}))

positivepets/views/email_views.py
"""
The email module has four functions:
    - email_folder_show(request, folder):  show either the inbox or sent mail
    - email_read_show(request, email_id):  show the email in its own page and mark it read
    - email_compose_show(request, reply_type, email_id): display a blank email in a pop-out window.
        - if reply or reply-all, fill in recipients and previous msg/subj
    - email_send(request): save the new rows down to the DB and close the window

Notes:
    This doesn't actually send email.  It's just a closed-system toy email built on a single DB table.
    The table positivepets_mail stores one line for each email, and repeats the whole record for each recipient.
    msg_id is a common identifier in each of these repeated rows - it is used to collect recipients for 'reply_all'
        - this will be inefficient when the DB is larger - plan is to restructure to avoid this repetition.
    each row contains a status that changes from 'unread' (1) to read (2) when it is viewed by the recipient
    The model name remains "Mail" and not "Email" because of MySQL migration issues
    This module uses Function Based Views - arbitrary choice just to learn FBV
"""

from datetime import datetime
from django.db.models import Max
from django.shortcuts import render
from positivepets.models import Mail, CustomUser
from positivepets.forms import EmailForm
from positivepets.utils.utils import get_active_friendgroup, add_standard_context

EMAIL_STATUS_UNREAD = 1
EMAIL_STATUS_READ = 2

def email_send(request):
    mx = Mail.objects.all().aggregate(Max('msg_id'))
    msg_id = mx['msg_id__max'] + 1
    recipient_list = request.POST.getlist('recipients')
    form = EmailForm(request.POST)
    form.fields['recipients'].queryset = CustomUser.objects.filter(id__in=get_active_friendgroup(request.user.id)).exclude(id=request.user.id).exclude(username='admin')

    if form.is_valid():
        for r in recipient_list:
            m = Mail()
            m.msg_id = msg_id
            m.timestamp = datetime.now()
            m.sender = request.user
            m.status = EMAIL_STATUS_UNREAD
            m.subject = request.POST['subject']
            m.message = request.POST['message']
            m.recipient = CustomUser.objects.get(id=int(r))
            m.save()
        return render(request, 'positivepets/close_me.html')

    context = add_standard_context(request, {}, request.user)
    context['subject'] = request.POST['subject']
    context['message'] = request.POST['message']
    context['recipient_list'] = recipient_list
    context['form'] = form

    return render(request, 'positivepets/email_folder.html', context)


def email_read_show(request, email_id):
    """
    Show the email on its own page.
    Change the status in the DB to "read"
    Make the recipients into a comma-separated list for display
    """

    email = Mail.objects.get(id=email_id)
    email.status = EMAIL_STATUS_READ
    email.save()

    recipient_list = list(Mail.objects.filter(msg_id=email.msg_id))
    my_list = [o.recipient.username.title() for o in recipient_list]
    recipient_string = ", ".join(my_list)
    context = {'email': email, 'recipients': recipient_string}

    return render(request, 'positivepets/email_read.html', context)

def email_compose_show(request, reply_type, email_id):

    context = add_standard_context(request, {}, request.user)
    active_friendgroup_members = CustomUser.objects.filter(id__in=get_active_friendgroup(request.user.id)).exclude(id=request.user.id)
    context['user_list'] = active_friendgroup_members


    if reply_type == 'none':
        form = EmailForm()
        form.fields['recipients'].queryset = active_friendgroup_members

    elif reply_type == 'reply':
        msg = Mail.objects.get(id=email_id)
        form = EmailForm(initial={'message': "\n\n <<<<< previous message: >>>>> \n " + msg.message, 'subject': msg.subject})
        context['recipient_list'] = [msg.sender]

    else: #reply_type == 'reply_all'
        msg = Mail.objects.get(id=email_id)
        form = EmailForm(initial={'message': "\n\n <<<<< previous message: >>>>> \n " + msg.message, 'subject': msg.subject})
        mail_objects = Mail.objects.filter(msg_id=msg.msg_id)
        recipient_list = [msg.sender]

        for m in mail_objects:
            recipient_list.append(m.recipient)

        context['recipient_list'] = recipient_list

    context['form'] = form
    return render(request, 'positivepets/email_compose.html', context)



def email_folder_show(request, folder):
    """
    Build recipient list out of multiple email records with common msg_id
    Build context lists for inbox and sent_mail
    """

    context = add_standard_context(request, {'folder': folder}, request.user)

    if folder == 'sent_mail':
        temp_sent_list = Mail.objects.filter(sender_id=request.user.id).filter(recipient__in=get_active_friendgroup(request.user.id)).order_by('-timestamp')
        sent_mail = []
        # fail nicely if there are no sent emails (new user)
        try:
            this_message = temp_sent_list[0]
            this_message.recipient.username = ""
            counter = 0
            for email in temp_sent_list:
                if email.msg_id == this_message.msg_id:
                    if counter == 0:
                        this_message.recipient.username = email.recipient.username.title()
                        counter = counter + 1
                    else:
                        this_message.recipient.username = ", ".join([this_message.recipient.username, email.recipient.username.title()])
                        counter = counter + 1
                else:
                    sent_mail.append(this_message)
                    this_message = email
                    counter = counter + 1

            sent_mail.append(this_message)
            context['sent_mail'] = sent_mail
        except:
            pass

    else:
        context['inbox'] = Mail.objects.filter(recipient_id=request.user).filter(sender__in=get_active_friendgroup(request.user.id)).order_by('-timestamp')

    return render(request, 'positivepets/email_folder.html', context)

positivepets/templates/positivepets/color_change_form.html
{% extends 'positivepets/base.html' %}
{% block title %} Favorite Color {% endblock %}

{% block body %}
<!--<div class="container-fluid">-->
<div class="container" style="border:1px solid #cecece;">
    <img src="{{user.picture.url}}" class="icon" style="border-radius:5px; border: 5px solid {{color}};">
    <span style="font-size:20pt;"> Update Color </span>
    <hr style="border-color:gray;">
    <h4>Pick Your Favorite Color</h4>
    <form class="form-horizontal" action="{% url 'positivepets:color_save_view' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="colors" class="col-sm-2 control-label">To:</label>
            <div class="col-sm-4">
                <select multiple class="form-control" id="colors" name="color" size="15" value="{{color_name}}">
                    {% for k,v in color_map.items %}
                        <option style="background-color:{{k}}; color:{{v.button_text_color}}"> {{v.display_name}} </option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button style="color:{{button_text_color}};background-color: {{user.color}};" type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

positivepets/templates/positivepets/group_admin.html
{% extends 'positivepets/base.html' %}
{% block title %} Message Board{% endblock %}
{% load tz %}

{% block body %}


Welcome to the Group Admin Page
<form action="{% url 'positivepets:group_add_view' %}">
    <input type="submit" value="Add Group">
</form>


<form action="{% url 'positivepets:group_add_view' %}" method="post">
    {% csrf_token %}
    {{ form}}
    <input type="submit" value="Submit">
</form>

<br>
<br>

{% for row in query_set %}
    <p>{{row.group__name}} {{row.user__username}}</p>
{% endfor %}



{% endblock %}

positivepets/templates/positivepets/profile.html
{% extends 'positivepets/base.html' %}
{% block body %}

{% load staticfiles %}
{% if user.is_authenticated %}


    <div class="container" style="border:1px solid #cecece;">
        <div class="row">
            <div class="col-md-9" style="font-size:20pt;">
                <img src="{{friend.picture.url}}" class="icon" style="border-radius:5px; border: 5px solid {{friend.color}};">
                {{friend.username | capfirst}}'s Profile
            </div>
            <div class="col-md-3">
                {% include 'positivepets/friendgroup_picker_template.html' with page='profile' pet_id=1 %}
            </div>
        </div>

        <hr style="border-color:gray;">
        <div class="row">

            <! COLUMN 1  -- FRIENDS >
            <div class="col-sm-3">
                <span style="font-size:14pt;"> Group: {{selected_friend_group.name}} </span><br>
                {% if not selected_friend_group %}
                    <p> You are not in a group.  Please ask your administrator to add you to a group. </p>
                {% endif %}

                {% for u in user_list %}
                    <a style="display:inline-block;text-decoration: none;" href="{% url 'positivepets:profile' u.id 'show'%}">

                        <img class="icon" src="{{u.picture.url}}"
                             style="border-radius:5px; margin:7px 7px 0px 7px; padding:0; border-width:5px;border-style:solid; border-color:{{u.color}};">
                        <div class="caption">
                            &nbsp
                            {% if u.id == user.id %}
                                <b> {{ u.username | capfirst }} </b>
                            {% else %}
                                {{ u.username | capfirst }}
                            {% endif %}
                        </div>
                    </a>

                 {% endfor %}

                <br><br> <span style="font-size:14pt;"> Recent Activity </span> <br>
                {% for row in activity_list %}
                    {{row}} <br>
                {% endfor %}
                <br>
            </div>

            <!-- COLUMN 2 -- PICTURE -->
            <div class="col-sm-7">
                <div class="row">
                    <div class="col-sm-7">
                        <div>
                            <a href="{% url 'positivepets:user_pets_show' friend.id %}">
                                <img src="{{friend.picture.url}}"  style="border-radius:5px; border: 5px solid {{friend.color}}; height:100%; width:100%; object-fit: cover;">
                            </a>
                        </div>

                        {% if friend.id == user.id %}

                            <form class="form-inline" role="form" enctype="multipart/form-data" action="" method="post" >
                                {% csrf_token %}
                                <div class="col-sm-12" style="padding: 0px 25px 0 5px;">

                                    <div style="width:100%;">
                                        <button  formaction="{% url 'positivepets:bio_edit' %}"
                                                style="margin:1% 0.5% 0 1.5%; width:31%; color:{{button_text_color}}; background-color:{{friend.color}};border-color:gray;" type="submit"
                                                class="btn btn-default mr-2" >Bio</button>

                                        <button formaction="{% url 'positivepets:color_change_view' %}"
                                                style="margin:1% 0.5% 0 0; width:31%;  color:{{button_text_color}}; background-color:{{friend.color}};border-color:gray;" type="submit"
                                                class="btn btn-default">Color</button>

                                        <button formaction="{% url 'positivepets:user_picture_edit' %}"
                                                style="margin:1% 0 0 0; width:31%;  color:{{button_text_color}}; background-color:{{friend.color}};border-color:gray;" type="submit"
                                                class="btn btn-defa ult" >Picture</button>
                                    </div>
                                </div>


                                {% if action == 'edit_picture' %}
                                <div class="row">
                                    <div col class="col-sm-7" style="border:1px solid #cecece;">
                                        <div class="form-group" style="margin:0px;">
                                            <input type="file" name="picture">
                                        </div>

                                        <div class="form-group" style="margin:0px;">
                                            <button formaction="{% url 'positivepets:user_picture_save' %}" type="submit" class="btn btn-default btn-small" >Go</button>
                                        </div>
                                    </div>
                                    <div col class="col-sm-5">

                                    </div>
                                </div>
                                {% endif %}
                            </form>
                            {% if action == 'edit_bio' %}
                            <div class="row">
                                <form class="form-horizontal" action="{% url 'positivepets:bio_save' %}" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <textarea class="form-control" name="bigtext" cols="60" rows="10"> {{friend.bio}} </textarea>
                                    </div>

                                    <div  class="form-group">
                                        <button style="background-color:{{color}};border-color:gray;" type="submit" class="btn btn-default">Save</button>
                                    </div>
                                </form>
                            </div>
                            {% else %} <! show display text and edit button>
                               <!-- <br><br><br><span style="font-size:14pt;"> All About Me </span> <br> {{friend.bio}}<br> -->
                            {% endif %}

                        {% else %} <! show display text and edit button>
                            <!--<br>
                            <p style="margin: 0 0 0 10px; font-size:14pt;"> All About {{friend.username | capfirst}} </p>
                            <p style="margin: 0 0 0 10px;">{{friend.bio}}</p> -->
                        {% endif %} <!-- friend == user -->
                    <br>
                    </div>

                    <div class="col-sm-5">

                        <span style="font-size:14pt;">
                            <p> Profile Details </p>
                        </span>

                        Name: {{friend.username | capfirst}} <br>
                        Town: {{friend.city | capfirst}}<br>
                        Birthday: {{friend.birthday | date:"F jS"}}<br>
                        Favorite Color: {{color_display_name | capfirst}}<br>
                        <br>
                        <!--<br> Invited By: {{friend.invitedby.username | capfirst}}-->


                        <form class="form-horizontal" action="{% url 'positivepets:user_pets_show' friend.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            <button style="margin:10px 10px 10px 0; width:80%; color:{{button_text_color}}; background-color:{{friend.color}};border-color:gray;" type="submit" class="btn btn-default">{{friend.username | capfirst}}'s Pets</button>
                        </form>
                        <br>

                        {% if friend.id == user.id %}
                        <span style="font-size:14pt;"> All About Me </span> <br> {{friend.bio}}<br>
                        {% else %}
                            <p style="font-size:14pt;"> All About {{friend.username | capfirst}} (by {{friend.username | capfirst}}) </p>
                            <p>{{friend.bio}}</p>
                        {% endif %}

                    </div>
                </div>  <!end first row inside big middle column>


            </div> <!-- end of big middle column -->

            <!-- COLUMN 3 -- PETS -->
             <div class="col-sm-2">
                 <span style="font-size:14pt;"> {{friend.username | capfirst}}'s Pets </span>
                 {% for p in pet_list %}
                     <a href="{% url 'positivepets:pet_detail' p.id 'show' %}">
                         <div class="row">
                             <img src="{{p.picture.url}}" style="margin:0 20px 0 0; border-radius:5px; border: 5px solid {{friend.color}}; height:90%; width:90%; object-fit: cover;">
                         </div>
                     </a>
                    <br>
                 {% endfor %}
             </div>
        </div>  <!-- end outer row -->
    </div> <!-- end container -->

{% else %}
    Welcome to Positive Pets.
{% endif %}
{% endblock %}

positivepets/templates/positivepets/user_pets.html
{% extends 'positivepets/base.html' %}

{% block body %}
<div class="container-fluid">
    <div class="container" style="border:1px solid #cecece;">

         <div class="row">
             <div class="col-md-9" style="font-size:20pt;">
                 <a href="{% url 'positivepets:profile' user.id 'show' %}">
                     <img src="{{friend.picture.url}}" class="icon" style="border-color:{{friend.color}}; border-radius:5px;">
                 </a>
                 <span style="font-size:20pt;"> {{friend.username | capfirst}}'s Pets:</span>
             </div>

             <div class="col-md-3">

             </div>
        </div>

        <hr style="border-color:gray;">

        <div class="row-md-4">
            {% for pet in pet_list %}

                <div class="col-md-4">
                    <a href="{% url 'positivepets:pet_detail' pet.id 'show' %}">
                        <img src="{{pet.picture.url}}" class="petpicture">
                    </a>

                    <h2> {{ pet.name }} </h2>

                    <a href="{% url 'positivepets:pet_detail' pet.id 'show' %}" class="btn btn-default btn-sm" style="color:{{button_text_color}}; background-color:{{color}};"> View Details </a>
                    {% if friend.username == user.username %}

                        <a href="{% url 'positivepets:pet_update' pet.id %}" class="btn btn-default btn-sm" style="color:{{button_text_color}}; background-color:{{color}};"> Update </a>

                        <form action="{% url 'positivepets:pet_delete' pet.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="pet_id" value="{{pet.id}}"/>
                            <button type="submit" class="btn btn-default btn-sm" style="color:{{button_text_color}}; background-color:{{color}};">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>

                        <!-- Favorite
                        <a href="#" class="btn btn-default btn-sm btn-favorite">
                            <span class="glyphicon glyphicon-star" style="background-color:{{color}};border-color:gray;"></span>
                        </a> -->

                    {% endif %}
                    <br><br>
                </div>


            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}